CONFIG_SYS_MMCSD_FS_BOOT_PARTITION=y
CONFIG_SYS_SPI_U_BOOT_OFFS=0x170000
CONFIG_BOOTM_NETBSD=y
CONFIG_BOARD_EARLY_INIT_F=y
CONFIG_BOOTM_VXWORKS=y
CONFIG_IS_MODULE(option)="config_enabled(CONFIG_VAL(option ##_MODULE))"
CONFIG_SYS_LOAD_ADDR=0x8000000
CONFIG_SYS_MEMTEST_SCRATCH=0x10800000
CONFIG_SYS_HELP_CMD_WIDTH=8
CONFIG_SYS_BARGSIZE=$(CONFIG_SYS_CBSIZE)
CONFIG_BOOTM_RTEMS=y
CONFIG_SYS_CBSIZE=2048
CONFIG_BOOTM_LINUX=y
CONFIG_THOR_RESET_OFF=y
CONFIG_SYS_SPL_MALLOC_SIZE=0x100000
CONFIG_SYS_SPL_ARGS_ADDR=0x8000000
CONFIG_SPL_BUILD=y
CONFIG_SYS_MALLOC_LEN="(CONFIG_ENV_SIZE + 0x2000000)"
CONFIG_ZYNQMP_PSU_INIT_ENABLED=y
CONFIG_SYS_BOOTM_LEN="(60 * 1024 * 1024)"
CONFIG_SYS_DEF_EEPROM_ADDR=$(CONFIG_SYS_I2C_EEPROM_ADDR)
CONFIG_SPL_FS_LOAD_ARGS_NAME="u-boot.bin"
CONFIG_SYS_MMCSD_RAW_MODE_ARGS_SECTOR=0
CONFIG_ARM_DCC=y
CONFIG_BOOTM_PLAN9=y
CONFIG_IS_BUILTIN(option)="config_enabled(CONFIG_VAL(option))"
CONFIG_SPL_TEXT_BASE=0xfffc0000
CONFIG_SYS_MAXARGS=64
CONFIG_SYS_PBSIZE="(CONFIG_SYS_CBSIZE + sizeof(CONFIG_SYS_PROMPT) + 16)"
CONFIG_BOARDDIR="board/xilinx/zynqmp"
CONFIG_SPL_LOAD_FIT_ADDRESS=0x10000000
CONFIG_SPL_STACK=0xfffffffc
CONFIG_SYS_MAX_FLASH_SECT=512
CONFIG_REMAKE_ELF=y
CONFIG_SYS_BOOT_RAMDISK_HIGH=y
CONFIG_ZLIB=y
CONFIG_GICV2=y
CONFIG_BOOTP_BOOTFILESIZE=y
CONFIG_BOOTP_MAY_FAIL=y
CONFIG_PANIC_HANG=y
CONFIG_GZIP=y
CONFIG_SYS_DFU_DATA_BUF_SIZE=0x1800000
CONFIG_SYS_MMCSD_RAW_MODE_ARGS_SECTORS=0
CONFIG_SPL_MAX_SIZE=0x40000
CONFIG_SYS_SPI_ARGS_OFFS=0xa0000
CONFIG_SYS_BAUDRATE_TABLE="{ 4800, 9600, 19200, 38400, 57600, 115200 }"
CONFIG_VAL(option)="config_val(option)"
CONFIG_SUPPORT_EMMC_BOOT=y
CONFIG_EXTRA_ENV_BOARD_SETTINGS=""kernel_addr=0x800000initrd_addr=0xa000000initrd_size=0x20000000fdt_addr=40000000fdt_high=0x100000000loadbootenv_addr=0x1000000sdbootdev=00kernel_offset=0x2800000fdt_offset=0x2000000kernel_size=0x1e000000fdt_size=0x800000bootenv=uEnv.txt0partid=auto0loadbootenv=load mmc $sdbootdev:$partid ${loadbootenv_addr} ${bootenv}0importbootenv=echo Importing environment from SD ...; env import -t ${loadbootenv_addr} $filesize0sd_uEnvtxt_existence_test=test -e mmc $sdbootdev:$partid /uEnv.txt0sata_root=if test $scsidevs -gt 0; then setenv bootargs $bootargs root=/dev/sda rw rootfstype=ext4; fi0sataboot=run xilinxcmd && load scsi 0 80000 boot/Image && load scsi 0 $fdt_addr boot/system.dtb && booti 80000 - $fdt_addr0netboot=run xilinxcmd && tftpboot 10000000 image.ub && bootm0qspiboot=run xilinxcmd && sf probe 0 0 0 && sf read $fdt_addr $fdt_offset $fdt_size && sf read $kernel_addr $kernel_offset $kernel_size && booti $kernel_addr - $fdt_addr0uenvboot=if run sd_uEnvtxt_existence_test; then run loadbootenv; echo Loaded environment from ${bootenv}; run importbootenv; fi; if test -n $uenvcmd; then echo Running uenvcmd ...; run uenvcmd; fi0sdboot=run xilinxcmd && mmc dev $sdbootdev && mmcinfo && run uenvboot || run sdroot$sdbootdev; load mmc $sdbootdev:$partid $fdt_addr system.dtb && load mmc $sdbootdev:$partid $kernel_addr Image && booti $kernel_addr - $fdt_addr0emmcboot=run sdboot0nandboot=run xilinxcmd && nand info && nand read $fdt_addr $fdt_offset $fdt_size && nand read $kernel_addr $kernel_offset $kernel_size && booti $kernel_addr - $fdt_addr0xen_prepare_dt=fdt addr $fdt_addr && fdt resize 128 && fdt set /chosen \#address-cells <1> && fdt set /chosen \#size-cells <1> && fdt mknod /chosen dom0 && fdt set /chosen/dom0 compatible "xen,linux-zimage" "xen,multiboot-module" && fdt set /chosen/dom0 reg <0x80000 0x$filesize> && fdt set /chosen xen,xen-bootargs "console=dtuart dtuart=serial0 dom0_mem=768M bootscrub=0 maxcpus=1 timer_slop=0" && fdt set /chosen xen,dom0-bootargs "console=hvc0 earlycon=xen earlyprintk=xen maxcpus=1 clk_ignore_unused"0xen_prepare_dt_qemu=run xen_prepare_dt && fdt set /cpus/cpu@1 device_type "none" && fdt set /cpus/cpu@2 device_type "none" && fdt set /cpus/cpu@3 device_type "none" && fdt rm /cpus/cpu@1 compatible && fdt rm /cpus/cpu@2 compatible && fdt rm /cpus/cpu@3 compatible0xen=run xilinxcmd && tftpb $fdt_addr system.dtb &&  tftpb 0x80000 Image &&run xen_prepare_dt && tftpb 6000000 xen.ub && tftpb 0x1000000 image.ub && bootm 6000000 0x1000000 $fdt_addr0xen_qemu=run xilinxcmd && tftpb $fdt_addr system.dtb && tftpb 0x80000 Image && run xen_prepare_dt_qemu && tftpb 6000000 xen.ub && tftpb 0x1000000 image.ub && bootm 6000000 0x1000000 $fdt_addr0jtagboot=run xilinxcmd && tftpboot 80000 Image && tftpboot $fdt_addr system.dtb && tftpboot 6000000 rootfs.cpio.ub && booti 80000 6000000 $fdt_addr0nosmp=setenv bootargs $bootargs maxcpus=10nfsroot=setenv bootargs $bootargs root=/dev/nfs nfsroot=$serverip:/mnt/sata,tcp ip=$ipaddr:$serverip:$serverip:255.255.255.0:zynqmp:eth0:off rw0sdroot0=setenv bootargs $bootargs root=/dev/mmcblk0p2 rw rootwait0sdroot1=setenv bootargs $bootargs root=/dev/mmcblk1p2 rw rootwait0android=setenv bootargs $bootargs init=/init androidboot.selinux=disabled androidboot.hardware=$board0android_debug=run android && setenv bootargs $bootargs video=DP-1:1024x768@60 drm.debug=0xf0usb_dfu_spl=booti $kernel_addr - $fdt_addr0usbhostboot=usb start && load usb 0 $fdt_addr system.dtb && load usb 0 $kernel_addr Image && booti $kernel_addr - $fdt_addr0xilinxcmd=echo !!! && echo !!! Booting cmd is deprecated (will be removed in 2020). && echo !!! Please move to distro bootcmd. && echo !!!0" PARTS_DEFAULT"
CONFIG_SYS_SPL_MALLOC_START=0x20000000
CONFIG_SPL_BSS_MAX_SIZE=0x80000
CONFIG_SPL_FS_LOAD_KERNEL_NAME="atf-uboot.ub"
CONFIG_SPL_BSS_START_ADDR=0x0
CONFIG_SPL_PAD_TO=$(CONFIG_SPL_MAX_SIZE)
CONFIG_EXTRA_ENV_SETTINGS="CONFIG_EXTRA_ENV_BOARD_SETTINGS ENV_MEM_LAYOUT_SETTINGS BOOTENV DFU_ALT_INFO"
CONFIG_SYS_INIT_SP_ADDR=$(CONFIG_SYS_TEXT_BASE)
CONFIG_SYS_MEMTEST_END=1000
CONFIG_SYS_SUPPORT_64BIT_DATA=y
CONFIG_SYS_SPI_KERNEL_OFFS=0x80000
CONFIG_CLOCKS=y
CONFIG_SYS_FAULT_ECHO_LINK_DOWN=y
CONFIG_SYS_MEMTEST_START=0
CONFIG_CPU_ARMV8=y
CONFIG_LMB=y
CONFIG_SYS_SPI_ARGS_SIZE=0xa0000
CONFIG_IS_ENABLED(option)="(config_enabled(CONFIG_VAL(option)) || config_enabled(CONFIG_VAL(option ##_MODULE)))"
CONFIG_SYS_MMCSD_RAW_MODE_KERNEL_SECTOR=0
CONFIG_SPL_FS_LOAD_PAYLOAD_NAME="u-boot.img"
